name: ModificationMaster
version: 1.8
main: me.setloth.modificationMaster.ModificationMaster
api-version: '1.21'
authors: [ Setloth ]
depend: [  ]
commands:
  sort:
    usage: /sort [block]
    description: Sorts your inventory or the target chest
  endchest:
    usage: /e[nd(er)]c[hest]
    aliases: [echest, enderchest, ec]
    description: Opens your ender chest on the go!
  craft:
    usage: /[craft(ing) | workbench]
    aliases: [crafting, workbench]
    description: Open a crafting table anywhere!
  veintoggle:
    usage: /veintoggle
    aliases: [vt]

